CREATE DATABASE SATHYABAMA;
USE SATHYABAMA;
CREATE TABLE PRODUCT(PRODUCT_ID INT, PRODUCT_NAME CHAR(50),PRICE FLOAT,AVAILABLE CHAR(5));
INSERT INTO PRODUCT VALUES(1,'BOOK1',100.7,'YES');
SELECT * FROM PRODUCT;
UPDATE PRODUCT SET PRODUCT_NAME ='THE WINGS OF FIRE ' WHERE PRODUCT_ID = 1;
SELECT * FROM PRODUCT;
DELETE FROM PRODUCT WHERE PRODUCT_ID = 1;
SET SQL_SAFE_UPDATES = 0;
SELECT * FROM PRODUCT;
INSERT INTO PRODUCT VALUES(1,'BOOK1',100.7,'YES');
INSERT INTO PRODUCT VALUES(2,'BOOK2',50,'YES');
SELECT * FROM PRODUCT;
DELETE FROM PRODUCT WHERE PRODUCT_ID = 1;
DELETE FROM PRODUCT WHERE PRODUCT_ID = 2;

SELECT pi();
SELECT sqrt(24);
SELECT  mod(25,6);
USE SAKILA;
SELECT * FROM SAKILA.ACTOR;
SELECT * FROM ACTOR order by FIRST_NAME;
SELECT * FROM ACTOR ORDER BY FIRST_NAME ASC;
SELECT * FROM ACTOR order by FIRST_NAME DESC;
SELECT * FROM ACTOR order by 1;
SELECT * FROM ACTOR order by 1 desc;
SELECT * FROM ACTOR order by 2 desc;
SELECT * FROM ACTOR where First_name = 'julia';
SELECT * FROM ACTOR WHERE ACTOR_ID <3;
SELECT * FROM ACTOR WHERE FALSE;
SELECT * FROM ACTOR WHERE 1=2;
SELECT ROUND(50.545);
SELECT ROUND(50.467);
SELECT ROUND(50.467,0);
SELECT ROUND(50.467,2);
SELECT ROUND(-1.23);
SELECT ROUND(-1.58);
SELECT ROUND(-1.58,2);
SELECT ceiling(-1.8);
SELECT FLOOR(-1.8);
SELECT FLOOR(7.4);
SELECT CEILING(7.4);
-- STRING OPERATORS
SELECT '1' + '1' ;
SELECT '1' + 'ABC' ;
SELECT CONCAT('1','ABC');
SELECT concat('1','ABC');
 
SELECT FIRST_NAME , LAST_NAME, CONCAT(FIRST_NAME, ' ',LAST_NAME) FROM ACTOR ;


CREATE DATABASE TEST;
USE TEST;
SHOW DATABASES;
-- STATIC VALUES
SELECT Today is wednesday
--arithmatic operation
SELECT SQRT(25);
SELECT * FROM SAKILA.ACTOR;
--SORT OREDER
SELECT  * FROM ACTOR ORDER BY FIRST_NAME DESC;

USE SAKILA;
SELECT * FROM ACTOR ORDER BY FIRST_NAME ASC;
-- SORT  OREDR BY COLOUMN NO
SELECT * FROM ACTOR ORDER BY 1;
-- FILTERING RECORD
SELECT * FROM ACTOR FIRST_NAME='JULIA';
 SELECT ROUND(2.6);
 
 SELECT ROUND(2600.34,-2);
 SELECT ROUND(-1.4);
 SELECT CEILING(2.3);
 SELECT FLOOR (4.5);
 SELECT CEILING(-2.7);
 SELECT FLOOR(-4.5);
 -- STRING OPERATION
 -- SELECT '1'+'1';- -ARITHMATIC OPERATION
 SELECT '1'+'ABC1';
 SELECT CONCAT('1','2');
 SELECT CONCAT('1','ABC');
 -- USER DEFINED COLOUMN HEADING
 SELECT CONCAT('1','ABC1') AS ' VALUE';
 SELECT FIRST_NAME,LAST_NAME,CONCAT(FIRST_NAME,LAST_NAME) FROM ACTOR;
 SELECT FIRST_NAME,LAST_NAME,CONCAT(FIRST_NAME,' ',LAST_NAME) FROM ACTOR;
 USE BOTREE;
 SELECT * FROM EMPLOYEE;
 SELECT SALARY,EMPLOYEE_NAME, CONCAT(SALARY, ' ' ,EMPLOYEE_NAME) FROM EMPLOYEE;
 USE SAKILA;
-- GET THE INITIALS--
SELECT LAST_NAME,LEFT(LAST_NAME,1) FROM ACTOR;
SELECT  FIRST_NAME,LAST_NAME,CONCAT(FIRST_NAME,'.',LEFT(LAST_NAME,1)) AS 'NAME WITH INITIALS' FROM ACTOR;
USE SAKILA;
-- EQUAL
SELECT * FROM FILM;
SELECT FILM_ID,TITLE,RELEASE_YEAR FROM FILM WHERE FILM_ID=4;
SELECT FILM_ID,TITLE,RELEASE_YEAR FROM FILM WHERE RELEASE_YEAR=2006;
-- GREATERTHAN
SELECT FILM_ID,TITLE,RELEASE_YEAR FROM  FILM WHERE  FILM_ID<3;
SELECT FILM_ID,TITLE,RELEASE_YEAR FROM FILM WHERE TITLE<' GOLDFINGER';
SELECT * FROM CITY;
SELECT CITY_ID,CITY,COUNTRY_ID FROM CITY WHERE CITY_ID=10;
SELECT CITY_ID,CITY,COUNTRY_ID FROM CITY WHERE CITY='AKISHIMA';
-- LESSERTHEN
SELECT CITY_ID,CITY,COUNTRY_ID FROM CITY WHERE COUNTRY_ID >50 ORDER BY COUNTRY_ID DESC;
SELECT CITY_ID,CITY,COUNTRY_ID ,LAST_UPDATE FROM CITY WHERE CITY<'ABHA';


USE SAKILA;

SELECT * FROM FILM;
 -- SELECT FILM_ID , TITLE ,CONCAT ( FILM_ID , TITLE ) FROM FILM AS '' FROM FILM;
SELECT * FROM ACTOR WHERE FIRST_NAME = 'KENNETH';
SELECT * FROM ACTOR  WHERE FIRST_NAME = 'KENNETH' OR ACTOR_ID > 100 ;
SELECT * FROM ACTOR WHERE FIRST_NAME = 'KENNETH' AND ACTOR_ID < 100 ;
SELECT ACTOR_ID ,FIRST_NAME , LAST_NAME FROM SAKILA.ACTOR WHERE NOT ACTOR_ID = 5;
SELECT ACTOR_ID ,FIRST_NAME , LAST_NAME FROM SAKILA.ACTOR WHERE NOT ACTOR_ID <> 5;
SELECT * FROM SAKILA.ACTOR WHERE FIRST_NAME = 'KENNETH' OR ACTOR_ID <100 AND LAST_NAME = 'TEMPLE';
SELECT * FROM SAKILA.ACTOR WHERE (FIRST_NAME = 'KENNETH' OR ACTOR_ID <100 ) AND LAST_NAME = 'TEMPLE';
SELECT * FROM SAKILA.ACTOR WHERE NOT ( FIRST_NAME = 'KENNETH' OR (ACTOR_ID <100 AND LAST_NAME = 'TEMPLE'));
SELECT * FROM SAKILA.ACTOR WHERE FIRST_NAME = 'KENNETH' OR NOT( ACTOR_ID <100 AND LAST_NAME = 'TEMPLE');
-- CREATING TABLES
SELECT * FROM ACTORSAMPLE1;
DROP TABLE ACTORSAMPLE1;
CREATE TABLE ACTORSAMPLE1 ( ACTOR_ID SMALLINT NOT NULL, FIRST_NAME VARCHAR(50) NULL);
SELECT * FROM ACTORSAMPLE1;
INSERT INTO ACTORSAMPLE1 VALUES (1, 'RAMBO');
INSERT INTO ACTORSAMPLE1 VALUES (2, NULL);
INSERT INTO ACTORSAMPLE1 VALUES (NULL, 'JOHN');
-- PRIMARY KEY
SELECT * FROM ACTORSAMPLE2;
DROP TABLE ACTORSAMPLE2;
CREATE TABLE ACTORSAMPLE2 ( ACTOR_ID SMALLINT NOT NULL PRIMARY KEY, FIRST_NAME VARCHAR(50) NULL);
SELECT * FROM ACTORSAMPLE2;
INSERT INTO ACTORSAMPLE2 VALUES (1, 'RAMBO');
INSERT INTO ACTORSAMPLE2 VALUES (2, NULL);
INSERT INTO ACTORSAMPLE2 VALUES (NULL, 'JOHN');
INSERT INTO ACTORSAMPLE2 VALUES (3, 'RAMBO');
DESCRIBE ACTORSAMPLE2;
SELECT CURRENT_TIMESTAMP;
DROP TABLE ACTORSAMPLE2;

-- CREATE A TABLE
CREATE TABLE ACTORSAMPLE
(
actor_id SMALLINT NOT NULL AUTO_INCREMENT,
FIRST_NAME VARCHAR(50) NOT NULL,
last_name VARCHAR(50),
LAST_UPDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (ACTOR_ID)
);
-- INSERT ALL FIELDS
INSERT INTO ACTORSAMPLE VALUES (100, 'GAUTHAM', 'BUDDHA', '2021-01-04');
SELECT * FROM ACTORSAMPLE;
-- INSERT SPECIFIC FIELDS
INSERT INTO ACTORSAMPLE (FIRST_NAME,last_name,LAST_UPDATE) VALUES  ( 'KRISHNA', 'LORD', '2020-01-04');
INSERT INTO ACTORSAMPLE (FIRST_NAME,last_name,LAST_UPDATE) VALUES  ( 'RAMA', 'KRISHNA', '2020-01-03');
INSERT INTO ACTORSAMPLE (FIRST_NAME,last_name,LAST_UPDATE) VALUES  ( 'SITA', 'KRISHNA', '2020-01-05');
INSERT INTO ACTORSAMPLE VALUES  (100, 'GAUTHAM', 'BUDDHA', '2019-01-04');
INSERT INTO ACTORSAMPLE VALUES  (DEFAULT, 'GAUTHAM', 'BUDDHA', '2020-01-04');
INSERT INTO ACTORSAMPLE VALUES  (NULL, 'GAUTHAM', 'BUDDHA', '2020-01-04');
INSERT INTO ACTORSAMPLE VALUES  (DEFAULT, NULL, 'BUDDHAS', '2020-01-04');
-- INSERT A RECORD AND LET SQL AUTOMATICALLY ADD THE LAST_UPDATE

INSERT INTO ACTORSAMPLE (first_name,last_name) VALUES ('GOUTHAM','BUDHA');
-- INSERT MULTIPLE VALUES
SELECT * FROM ACTORSAMPLE;
INSERT INTO ACTORSAMPLE (first_name,last_name) VALUES 
('GOUTHAM1','BUDHA'),
('GOUTHAM2','BUDHA'),
('GOUTHAM3','BUDHA');
INSERT INTO ACTORSAMPLE VALUES  (100, 'GAUTHAM', 'BUDDHA', '2019-01-04');
SET SQL_SAFE_UPDATES = 0;
-- DELETE ALL ROWS
DELETE FROM ACTORSAMPLE;
DELETE FROM ACTORSAMPLE WHERE ACTOR_ID = 100;
DELETE FROM ACTORSAMPLE WHERE FIRST_NAME = 'GAUTHAM' AND LAST_NAME = 'BUDDHA';
-- REMOVE A TABLE (STRUCTURE AND THE 
DROP TABLE ACTORSAMPLE;
SELECT * FROM ACTOR WHERE FIRST_NAME = 'PENELOPE' AND LAST_NAME = 'cronyn';
SELECT * FROM PRODUCT WHERE FIRST_NAME LIKE 'PE%' AND LAST_NAME = 'GUINESS';





















































